// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_qpow`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-06-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Pro-4.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --pallet
// pallet-qpow
// --extrinsic
// *
// --template
// ./.maintain/frame-weight-template.hbs
// --output
// ./pallets/qpow/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_qpow`.
pub trait WeightInfo {
	fn on_finalize() -> Weight;
}

// Hand-edited after the 120 s target landed, and the edit is one read.
// `adjust_difficulty` calls `Self::target_block_time()`, which reads
// `QPoW::TargetBlockTimeMs`, so `on_finalize` touches five keys where this file
// declared four and every block did a read its weight never paid for. The read
// is declared here; the `ref_time` and `proof_size` figures are still the
// measured ones from the run in the header, which is conservative for a single
// 8-byte value under the overlay. `benchmarking.rs` no longer warms that key in
// its setup, so a regeneration measures the read and blesses five.


/// Weights for `pallet_qpow` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `QPoW::CurrentDifficulty` (r:2 w:1)
	/// Proof: `QPoW::CurrentDifficulty` (`max_values`: Some(1), `max_size`: Some(64), added: 559, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockTime` (r:1 w:1)
	/// Proof: `QPoW::LastBlockTime` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockDuration` (r:0 w:1)
	/// Proof: `QPoW::LastBlockDuration` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::TargetBlockTimeMs` (r:1 w:0)
	/// Proof: `QPoW::TargetBlockTimeMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `680`
		//  Estimated: `1549`
		// Minimum execution time: 106_000_000 picoseconds.
		Weight::from_parts(109_000_000, 1549)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `QPoW::CurrentDifficulty` (r:2 w:1)
	/// Proof: `QPoW::CurrentDifficulty` (`max_values`: Some(1), `max_size`: Some(64), added: 559, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockTime` (r:1 w:1)
	/// Proof: `QPoW::LastBlockTime` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockDuration` (r:0 w:1)
	/// Proof: `QPoW::LastBlockDuration` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::TargetBlockTimeMs` (r:1 w:0)
	/// Proof: `QPoW::TargetBlockTimeMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `680`
		//  Estimated: `1549`
		// Minimum execution time: 106_000_000 picoseconds.
		Weight::from_parts(109_000_000, 1549)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
