// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_mining_rewards`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-08-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Q-Beasts-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --pallet=pallet_mining_rewards
// --steps=50
// --repeat=20
// --runtime=./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --genesis-builder=runtime
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/mining-rewards/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_mining_rewards`.
pub trait WeightInfo {
	fn on_finalize_rewarded_miner() -> Weight;
}

/// ZK-tree leaf inserts this pallet's `on_finalize` reserves: none.
///
/// `on_finalize` hands the credit to `Config::CoinbaseSink`, and the pool
/// appends the coinbase leaf inside its own `deposit_coinbase`.
/// `pallet-shielded`'s `on_initialize` reserves that append, the ciphertext and
/// the maps it writes, so reserving a leaf here too would charge every block
/// twice for one insert.
const MAX_LEAF_INSERTS: u64 = 0;

/// Non-tree storage for the worst-case finalize path.
///
/// Once per finalize: `CollectedFees` take (r1 w1) and put-back of dust (r1 w1),
/// the digest read for the author lookup, and the shielded pool's own read of
/// the value it stands behind.
const BASE_READS: u64 = 4;
const BASE_WRITES: u64 = 2;

/// PoV per fixed-base key (rounded up from `System::Account` MaxEncodedLen).
const BASE_KEY_POV: u64 = 2700;

/// Weights for `pallet_mining_rewards` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Reserved in `on_initialize` before extrinsics run. Leaf appends are priced
	/// at the flat marginal per-insert share ([`pallet_zk_tree::INSERT_LEAF_DB_OPS`]);
	/// the batched root recomputation's depth-dependent tail is reserved by the
	/// zk-tree pallet's own `on_initialize`.
	fn on_finalize_rewarded_miner() -> Weight {
		// Minimum execution time: 150_000_000 picoseconds.
		let (tree_reads, tree_writes) = pallet_zk_tree::INSERT_LEAF_DB_OPS;
		let hash_time =
			MAX_LEAF_INSERTS.saturating_mul(pallet_zk_tree::INSERT_LEAF_HASH_REF_TIME_PS);
		let proof_size = BASE_READS.saturating_mul(BASE_KEY_POV).saturating_add(
			MAX_LEAF_INSERTS
				.saturating_mul(tree_reads)
				.saturating_mul(pallet_zk_tree::TREE_KEY_POV),
		);
		Weight::from_parts(162_000_000_u64.saturating_add(hash_time), proof_size)
			.saturating_add(T::DbWeight::get().reads(
				BASE_READS.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_reads)),
			))
			.saturating_add(T::DbWeight::get().writes(
				BASE_WRITES.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_writes)),
			))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Same marginal per-insert pricing as `SubstrateWeight`, with `RocksDbWeight`
	/// in place of the runtime's configured `DbWeight`.
	fn on_finalize_rewarded_miner() -> Weight {
		// Minimum execution time: 150_000_000 picoseconds.
		let (tree_reads, tree_writes) = pallet_zk_tree::INSERT_LEAF_DB_OPS;
		let hash_time =
			MAX_LEAF_INSERTS.saturating_mul(pallet_zk_tree::INSERT_LEAF_HASH_REF_TIME_PS);
		let proof_size = BASE_READS.saturating_mul(BASE_KEY_POV).saturating_add(
			MAX_LEAF_INSERTS
				.saturating_mul(tree_reads)
				.saturating_mul(pallet_zk_tree::TREE_KEY_POV),
		);
		Weight::from_parts(162_000_000_u64.saturating_add(hash_time), proof_size)
			.saturating_add(RocksDbWeight::get().reads(
				BASE_READS.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_reads)),
			))
			.saturating_add(RocksDbWeight::get().writes(
				BASE_WRITES.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_writes)),
			))
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn proof_size_covers_base_and_tree_path_keys() {
		let reserved = <() as WeightInfo>::on_finalize_rewarded_miner();
		let (tree_reads, _) = pallet_zk_tree::INSERT_LEAF_DB_OPS;
		assert!(
			reserved.proof_size() >=
				BASE_READS * BASE_KEY_POV +
					MAX_LEAF_INSERTS * tree_reads * pallet_zk_tree::TREE_KEY_POV,
			"reserved PoV must cover every base key plus all tree path keys at \
			 CIRCUIT_MAX_TREE_DEPTH"
		);
	}

	#[test]
	fn base_covers_the_finalize_path() {
		// Once per finalize: `CollectedFees` take (r1 w1) and the dust put-back
		// (r1 w1), plus the digest read behind the author lookup and the
		// shielded pool's read of the value it stands behind. Nothing is minted
		// into an account and no leaf is charged here: the coinbase append is
		// reserved by `pallet-shielded`'s own `on_initialize`, which is what
		// `MAX_LEAF_INSERTS` being zero says.
		const FIXED_READS: u64 = 2;
		const FIXED_WRITES: u64 = 2;
		const AUTHOR_LOOKUP_READS: u64 = 2;

		assert_eq!(MAX_LEAF_INSERTS, 0, "the coinbase leaf is the sink pallet's to reserve");
		assert_eq!(
			BASE_READS,
			FIXED_READS + AUTHOR_LOOKUP_READS,
			"BASE_READS must cover the fee slot and the author lookup"
		);
		assert_eq!(
			BASE_WRITES, FIXED_WRITES,
			"BASE_WRITES must cover the fee slot, and nothing mints"
		);
	}
}
