//! The committed raw chain spec is what this binary exports, byte for byte.
//!
//! `node/chain-specs/qnero-testnet.json` is the file every operator of the
//! public testnet is handed, and its `.genesis.raw.top` carries the whole
//! compressed runtime wasm, so it is the one artifact no runtime upgrade
//! reaches: whoever holds it launches that genesis until somebody hands them
//! another file. It is generated by `scripts/build-testnet-spec.sh` and never
//! edited by hand, and this test is what makes that true rather than
//! aspirational. A preset edit that nobody re-exported fails here instead of
//! shipping a spec whose genesis the tree can no longer rebuild.
//!
//! The one field a deployment writes into the file after it is generated is
//! `bootNodes`. It sits outside genesis (`chain/docs/CHAINSPEC_CREATION.md`),
//! so filling it in does not move the genesis hash and nothing has to be
//! regenerated; the committed copy carries an empty list, because the peer id
//! of a seed node that does not exist yet is not a thing a repository can
//! know. Both cases are handled below, and the byte comparison is the live
//! one for as long as the committed list is empty.

use std::{path::PathBuf, process::Command};

const NODE: &str = env!("CARGO_BIN_EXE_qnero-node");

fn committed_spec_path() -> PathBuf {
	PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("chain-specs/qnero-testnet.json")
}

/// Export the spec, or `None` when this binary was built with no runtime wasm.
///
/// `SKIP_WASM_BUILD=1` leaves `WASM_BINARY` empty, and every preset builder
/// then returns its own "wasm not available". That one case is a skip, and
/// only when the variable is actually set, so a missing wasm for any other
/// reason is still a failure. The same rule as `naming_guard.rs`.
fn export() -> Option<Vec<u8>> {
	let output = Command::new(NODE)
		.args(["build-spec", "--chain", "qnero-testnet", "--raw", "--disable-default-bootnode"])
		.output()
		.unwrap_or_else(|error| panic!("running `{NODE} build-spec` failed: {error}"));
	if !output.status.success() {
		let stderr = String::from_utf8_lossy(&output.stderr);
		if std::env::var_os("SKIP_WASM_BUILD").is_some() && stderr.contains("wasm not available") {
			eprintln!(
				"SKIP_WASM_BUILD is set and this binary carries no runtime wasm; skipping the \
                 chain spec reproducibility check"
			);
			return None;
		}
		panic!("build-spec --chain qnero-testnet --raw failed: {stderr}");
	}
	Some(output.stdout)
}

#[test]
fn the_committed_testnet_spec_is_what_this_binary_exports() {
	let Some(exported) = export() else { return };
	let path = committed_spec_path();
	let committed = std::fs::read(&path).unwrap_or_else(|error| {
		panic!(
			"{} is missing or unreadable ({error}). Generate it with \
             scripts/build-testnet-spec.sh",
			path.display()
		)
	});

	let committed_json: serde_json::Value = serde_json::from_slice(&committed)
		.unwrap_or_else(|error| panic!("{} is not JSON: {error}", path.display()));
	let boot_nodes = committed_json["bootNodes"]
		.as_array()
		.unwrap_or_else(|| panic!("{} has no bootNodes array", path.display()));

	if boot_nodes.is_empty() {
		// The live assertion: every byte, the megabyte of runtime wasm
		// included. Reported by size and by the first differing offset,
		// because printing the difference itself would be the file.
		if exported != committed {
			let at = exported
				.iter()
				.zip(&committed)
				.position(|(a, b)| a != b)
				.unwrap_or_else(|| exported.len().min(committed.len()));
			panic!(
				"{} is not what this binary exports. Committed {} bytes, exported {} bytes, \
                 first difference at byte {at}. Regenerate it with \
                 scripts/build-testnet-spec.sh and commit the result.",
				path.display(),
				committed.len(),
				exported.len()
			);
		}
		return;
	}

	// A deployment has written its seed node into the committed file. Every
	// other byte still has to be what this binary exports, and each entry has
	// to be a multiaddr shaped like the one the runbook produces.
	let mut exported_json: serde_json::Value =
		serde_json::from_slice(&exported).expect("build-spec writes a JSON chain spec");
	for entry in boot_nodes {
		let address = entry
			.as_str()
			.unwrap_or_else(|| panic!("a bootNodes entry is not a string: {entry}"));
		let parts: Vec<&str> = address.split('/').collect();
		assert!(
			matches!(parts.as_slice(), ["", kind, _, "tcp", _, "p2p", _] if
                     *kind == "dns" || *kind == "dns4" || *kind == "dns6" || *kind == "ip4"),
			"the bootNodes entry {address:?} is not a /dns/<host>/tcp/<port>/p2p/<peer id> \
             multiaddr"
		);
	}
	exported_json["bootNodes"] = committed_json["bootNodes"].clone();
	assert_eq!(
		exported_json,
		committed_json,
		"{} differs from what this binary exports somewhere other than bootNodes. Regenerate \
         it with scripts/build-testnet-spec.sh, then put the bootnode list back.",
		path.display()
	);
}

/// What the committed spec says about itself, read off the file rather than
/// off a builder.
///
/// `naming_guard.rs` pins the same four fields on the spec the binary builds.
/// These are the ones in the file, which is a different artifact: a wallet, an
/// explorer or a miner handed this JSON reads its name, its id, its protocol
/// id and its token out of it, and the reproducibility check above would pass
/// just as happily on a file that was regenerated after a bad rename.
#[test]
fn the_committed_testnet_spec_names_the_testnet() {
	let path = committed_spec_path();
	let raw = std::fs::read(&path)
		.unwrap_or_else(|error| panic!("{} is missing or unreadable ({error})", path.display()));
	let spec: serde_json::Value =
		serde_json::from_slice(&raw).unwrap_or_else(|error| panic!("not JSON: {error}"));

	assert_eq!(spec["name"].as_str(), Some("Qnero Testnet"));
	assert_eq!(spec["id"].as_str(), Some("qnero-testnet"));
	assert_eq!(spec["protocolId"].as_str(), Some("qnero-testnet"));
	assert_eq!(spec["chainType"].as_str(), Some("Live"));
	assert_eq!(spec["properties"]["tokenSymbol"].as_str(), Some("QNR"));
	assert_eq!(spec["properties"]["tokenDecimals"].as_u64(), Some(12));
	assert_eq!(spec["properties"]["ss58Format"].as_u64(), Some(189));

	// Telemetry defaults on for a Live chain, and Qnero runs no telemetry
	// server. An endpoint here would publish a node name, a client version and
	// a block height to somebody else's server for every operator who took the
	// file, which is exactly what the three inherited presets used to do.
	let telemetry = &spec["telemetryEndpoints"];
	assert!(
		telemetry.is_null() || telemetry.as_array().is_some_and(|list| list.is_empty()),
		"the committed spec names a telemetry endpoint: {telemetry}"
	);

	// The raw genesis, present and carrying the runtime. `0x3a636f6465` is
	// `:code`.
	let top = spec["genesis"]["raw"]["top"]
		.as_object()
		.expect("a raw spec carries genesis.raw.top");
	let code = top
		.get("0x3a636f6465")
		.and_then(|value| value.as_str())
		.expect("the raw genesis carries :code");
	assert!(
		code.len() > 200_000,
		"genesis :code is {} characters, which is too small to be the runtime wasm. A binary \
         built with SKIP_WASM_BUILD set exports a stub here",
		code.len()
	);
}
