//! The committed raw chain spec is what this binary exports, byte for byte.
//!
//! `node/chain-specs/qnero-testnet.json` is the file every operator of the
//! public testnet is handed, and its `.genesis.raw.top` carries the whole
//! compressed runtime wasm, so it is the one artifact no runtime upgrade
//! reaches: whoever holds it launches that genesis until somebody hands them
//! another file. It is generated by `scripts/build-testnet-spec.sh` and never
//! edited by hand, and this test is what makes that true rather than
//! aspirational. A preset edit that nobody re-exported fails here instead of
//! shipping a spec whose genesis the tree can no longer rebuild.
//!
//! The one field a deployment writes into the file after it is generated is
//! `bootNodes`. It sits outside genesis (`chain/docs/CHAINSPEC_CREATION.md`),
//! so filling it in does not move the genesis hash and nothing has to be
//! regenerated. The committed copy carries the testnet's seed node, so the
//! comparison below is the second of its two forms: `bootNodes` is taken from
//! the committed file and every other byte still has to be what this binary
//! exports. The empty-list form stays because a fresh network has no peer id
//! for a repository to know yet.
//!
//! These tests answer for a binary that carries a real runtime wasm. A binary
//! built with `SKIP_WASM_BUILD` set exports a stub genesis, so there is nothing
//! to compare and the checks skip. A skip that nobody notices is the same as no
//! test, so set `QNERO_REQUIRE_WASM=1` and the skip becomes a failure: that is
//! what CI does, and what the release runbook's spec step relies on.
//!
//! They answer for the release profile specifically. `substrate-wasm-builder`
//! writes its artifacts under `target/<outer profile>/wbuild`, and the two
//! profiles produce different wasm: `target/debug/wbuild` holds an
//! uncompacted, uncompressed blob. The committed spec is generated by the
//! release binary the runbook ships, so `cargo test --release` is the
//! invocation that compares like with like, and a debug run fails on `:code`
//! alone. CI runs this target with `--release` for that reason.

use std::{path::PathBuf, process::Command};

const NODE: &str = env!("CARGO_BIN_EXE_qnero-node");

/// Refuse the stub-runtime skip when the caller asked for the real thing.
///
/// Returns to the caller only when the skip is allowed, and says on stderr
/// which check it gave up, so a local run that produced no comparison says so
/// in its own output.
fn allow_the_stub_runtime_skip(what: &str) {
	assert!(
		std::env::var_os("QNERO_REQUIRE_WASM").is_none(),
		"QNERO_REQUIRE_WASM is set, so {what} has to run against a real runtime wasm. This \
         binary was built with SKIP_WASM_BUILD set and carries a stub. Rebuild qnero-node \
         without it."
	);
	eprintln!(
		"SKIP_WASM_BUILD is set and this binary carries no runtime wasm; skipping {what}. Set \
         QNERO_REQUIRE_WASM=1 to make this a failure."
	);
}

/// Where the committed spec's runtime is reproducible from.
///
/// `substrate-wasm-builder` names every chain crate by absolute path, cargo
/// hashes that path into symbol names, and the runtime wasm in genesis moves
/// with the checkout directory. `scripts/build-canonical-node.sh` has the
/// detail. So the byte comparison means something only for a build at this
/// path, and a build anywhere else is skipped, or refused under
/// `QNERO_REQUIRE_WASM`.
const CANONICAL_DIR: &str = "/tmp/qnero-spec-build/";

fn built_at_the_canonical_path() -> bool {
	let manifest = env!("CARGO_MANIFEST_DIR");
	if manifest.starts_with(CANONICAL_DIR) {
		return true;
	}
	assert!(
		std::env::var_os("QNERO_REQUIRE_WASM").is_none(),
		"QNERO_REQUIRE_WASM is set, but this node was built at {manifest}. The committed spec \
		 is reproducible only from a build under {CANONICAL_DIR}: run \
		 scripts/build-canonical-node.sh and test from there."
	);
	eprintln!(
		"this node was built at {manifest}, outside {CANONICAL_DIR}; skipping the committed \
		 spec comparison. scripts/build-canonical-node.sh builds where it applies."
	);
	false
}

/// Check source locations before compaction/compression can hide their bytes.
#[test]
fn runtime_wasm_uses_portable_source_paths() {
	let Some(wasm) = qnero_runtime::WASM_BINARY_BLOATY else {
		assert!(std::env::var_os("SKIP_WASM_BUILD").is_some(), "runtime WASM is required");
		allow_the_stub_runtime_skip("the runtime wasm source-path check");
		return;
	};
	assert!(wasm.starts_with(b"\0asm"), "inspect the uncompressed runtime");
	let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
	let source = manifest.parent().unwrap().parent().unwrap();
	let mut prefixes = vec![source.to_string_lossy().into_owned()];
	for name in ["CARGO_HOME", "HOME", "USERPROFILE"] {
		if let Some(path) = std::env::var_os(name) {
			let prefix = path.to_string_lossy().into_owned();
			if prefix.len() > 1 {
				prefixes.push(prefix);
			}
		}
	}
	for prefix in prefixes {
		// Name the prefix and show the bytes around the first hit, so a failure
		// on a machine nobody can log into says which path leaked and from where.
		if let Some(at) = wasm.windows(prefix.len()).position(|bytes| bytes == prefix.as_bytes()) {
			let from = at.saturating_sub(96);
			let to = (at + prefix.len() + 160).min(wasm.len());
			panic!(
				"runtime contains the local path {prefix:?} at byte {at}; inspect build-script \
				 remapping. Context: {:?}",
				String::from_utf8_lossy(&wasm[from..to]),
			);
		}
	}
}

fn committed_spec_path() -> PathBuf {
	PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("chain-specs/qnero-testnet.json")
}

/// Export the spec, or `None` when this binary was built with no runtime wasm.
///
/// `SKIP_WASM_BUILD=1` leaves `WASM_BINARY` empty, and every preset builder
/// then returns its own "wasm not available". That one case is a skip, and
/// only when the variable is actually set, so a missing wasm for any other
/// reason is still a failure. The same rule as `naming_guard.rs`, and
/// `QNERO_REQUIRE_WASM` closes the skip for a caller that needs the real
/// comparison.
fn export() -> Option<Vec<u8>> {
	let output = Command::new(NODE)
		.args(["build-spec", "--chain", "qnero-testnet", "--raw", "--disable-default-bootnode"])
		.output()
		.unwrap_or_else(|error| panic!("running `{NODE} build-spec` failed: {error}"));
	if !output.status.success() {
		let stderr = String::from_utf8_lossy(&output.stderr);
		if std::env::var_os("SKIP_WASM_BUILD").is_some() && stderr.contains("wasm not available") {
			allow_the_stub_runtime_skip("the chain spec reproducibility check");
			return None;
		}
		panic!("build-spec --chain qnero-testnet --raw failed: {stderr}");
	}
	Some(output.stdout)
}

#[test]
fn the_committed_testnet_spec_is_what_this_binary_exports() {
	if !built_at_the_canonical_path() {
		return;
	}
	let Some(exported) = export() else { return };
	let path = committed_spec_path();
	let committed = std::fs::read(&path).unwrap_or_else(|error| {
		panic!(
			"{} is missing or unreadable ({error}). Generate it with \
             scripts/build-testnet-spec.sh",
			path.display()
		)
	});

	let committed_json: serde_json::Value = serde_json::from_slice(&committed)
		.unwrap_or_else(|error| panic!("{} is not JSON: {error}", path.display()));
	let boot_nodes = committed_json["bootNodes"]
		.as_array()
		.unwrap_or_else(|| panic!("{} has no bootNodes array", path.display()));

	if boot_nodes.is_empty() {
		// The live assertion: every byte, the megabyte of runtime wasm
		// included. Reported by size and by the first differing offset,
		// because printing the difference itself would be the file.
		if exported != committed {
			let at = exported
				.iter()
				.zip(&committed)
				.position(|(a, b)| a != b)
				.unwrap_or_else(|| exported.len().min(committed.len()));
			panic!(
				"{} is not what this binary exports. Committed {} bytes, exported {} bytes, \
                 first difference at byte {at}. Regenerate it with \
                 scripts/build-testnet-spec.sh and commit the result.",
				path.display(),
				committed.len(),
				exported.len()
			);
		}
		return;
	}

	// A deployment has written its seed node into the committed file. Every
	// other byte still has to be what this binary exports, and each entry has
	// to be a multiaddr shaped like the one the runbook produces.
	let mut exported_json: serde_json::Value =
		serde_json::from_slice(&exported).expect("build-spec writes a JSON chain spec");
	for entry in boot_nodes {
		let address = entry
			.as_str()
			.unwrap_or_else(|| panic!("a bootNodes entry is not a string: {entry}"));
		let parts: Vec<&str> = address.split('/').collect();
		assert!(
			matches!(parts.as_slice(), ["", kind, _, "tcp", _, "p2p", _] if
                     *kind == "dns" || *kind == "dns4" || *kind == "dns6" || *kind == "ip4"),
			"the bootNodes entry {address:?} is not a /dns/<host>/tcp/<port>/p2p/<peer id> \
             multiaddr"
		);
	}
	exported_json["bootNodes"] = committed_json["bootNodes"].clone();
	if exported_json != committed_json {
		// Name the genesis keys that differ with their sizes. Printing both
		// values would be two copies of the whole runtime.
		let top = |json: &serde_json::Value| json["genesis"]["raw"]["top"].clone();
		let (exported_top, committed_top) = (top(&exported_json), top(&committed_json));
		let mut keys: Vec<String> = Vec::new();
		if let (Some(a), Some(b)) = (exported_top.as_object(), committed_top.as_object()) {
			for key in a.keys().chain(b.keys()) {
				if a.get(key) != b.get(key) && !keys.contains(key) {
					let size = |v: Option<&serde_json::Value>| {
						v.and_then(|v| v.as_str()).map_or(0, |v| v.len())
					};
					keys.push(key.clone());
					keys.push(format!(
						"(exported {} chars, committed {})",
						size(a.get(key)),
						size(b.get(key))
					));
				}
			}
		}
		panic!(
			"{} differs from what this binary exports somewhere other than bootNodes. \
			 Differing genesis keys: {keys:?}. Regenerate it with \
			 scripts/build-testnet-spec.sh, then put the bootnode list back.",
			path.display()
		);
	}
}

/// The one client-side seam that can execute different code for a block is
/// empty, and empty on purpose.
///
/// `codeSubstitutes` is a client-side seam. A node handed a spec with an entry
/// there runs different code for the block it names, which is that node forking
/// itself off rather than a power over anybody else. The runtime never sees the
/// field. The same is true of `--wasm-runtime-overrides`. Neither is an admin
/// key, and neither should be mistaken for one, but a spec that shipped a
/// non-empty map would make the "no admin keys" claim overstated for whoever
/// took the file. So the field is asserted rather than assumed: what the
/// repository hands operators carries nothing there.
#[test]
fn the_shipped_spec_carries_no_code_substitute() {
	let path = committed_spec_path();
	let raw = std::fs::read(&path)
		.unwrap_or_else(|error| panic!("{} is missing or unreadable ({error})", path.display()));
	let spec: serde_json::Value =
		serde_json::from_slice(&raw).unwrap_or_else(|error| panic!("not JSON: {error}"));

	let substitutes = &spec["codeSubstitutes"];
	assert!(
		substitutes.is_null() ||
			substitutes.as_object().is_some_and(|map| map.is_empty()),
		"the committed spec carries a code substitute: {substitutes}. A node that takes          this file would execute code other than the runtime in its own genesis"
	);
}

/// What the committed spec says about itself, read off the file rather than
/// off a builder.
///
/// `naming_guard.rs` pins the same four fields on the spec the binary builds.
/// These are the ones in the file, which is a different artifact: a wallet, an
/// explorer or a miner handed this JSON reads its name, its id, its protocol
/// id and its token out of it, and the reproducibility check above would pass
/// just as happily on a file that was regenerated after a bad rename.
#[test]
fn the_committed_testnet_spec_names_the_testnet() {
	let path = committed_spec_path();
	let raw = std::fs::read(&path)
		.unwrap_or_else(|error| panic!("{} is missing or unreadable ({error})", path.display()));
	let spec: serde_json::Value =
		serde_json::from_slice(&raw).unwrap_or_else(|error| panic!("not JSON: {error}"));

	assert_eq!(spec["name"].as_str(), Some("Qnero Testnet"));
	assert_eq!(spec["id"].as_str(), Some("qnero-testnet"));
	assert_eq!(spec["protocolId"].as_str(), Some("qnero-testnet"));
	assert_eq!(spec["chainType"].as_str(), Some("Live"));
	assert_eq!(spec["properties"]["tokenSymbol"].as_str(), Some("QNR"));
	assert_eq!(spec["properties"]["tokenDecimals"].as_u64(), Some(12));
	assert_eq!(spec["properties"]["ss58Format"].as_u64(), Some(189));

	// Telemetry defaults on for a Live chain, and Qnero runs no telemetry
	// server. An endpoint here would publish a node name, a client version and
	// a block height to somebody else's server for every operator who took the
	// file, which is exactly what the three inherited presets used to do.
	let telemetry = &spec["telemetryEndpoints"];
	assert!(
		telemetry.is_null() || telemetry.as_array().is_some_and(|list| list.is_empty()),
		"the committed spec names a telemetry endpoint: {telemetry}"
	);

	// The raw genesis, present and carrying the runtime. `0x3a636f6465` is
	// `:code`.
	let top = spec["genesis"]["raw"]["top"]
		.as_object()
		.expect("a raw spec carries genesis.raw.top");
	let code = top
		.get("0x3a636f6465")
		.and_then(|value| value.as_str())
		.expect("the raw genesis carries :code");
	assert!(
		code.len() > 200_000,
		"genesis :code is {} characters, which is too small to be the runtime wasm. A binary \
         built with SKIP_WASM_BUILD set exports a stub here",
		code.len()
	);
}
