#!/usr/bin/env bash
#
# Write the trusted-proxy list that makes every rate limit count callers.
#
#   sudo ./scripts/fetch-real-ip-ranges.sh [/etc/nginx/qnero-real-ip.conf]
#
# `packaging/nginx/00-qnero-common.conf` includes that path, so a host with no
# list fails `nginx -t` instead of serving a configuration whose limits have
# quietly become global. That is the whole design here: without a
# `set_real_ip_from` covering the CDN, nginx never rewrites `$remote_addr`,
# every request arrives from one of a handful of edge addresses, `limit_conn
# rpc_conn` becomes a cap on the number of WebSockets the entire internet may
# hold open at once, and the faucet's per-client window becomes one bucket.
#
# The ranges are fetched rather than committed because they change, and a
# stale list is two failures at once: a CDN range that is no longer trusted is
# a caller counted wrong, and a range that is trusted and is no longer the
# CDN's is a client whose own CF-Connecting-IP header is believed.
#
# Offline, or against a list kept elsewhere:
#
#   QNERO_CDN_IPV4_URL=file:///path/ips-v4 QNERO_CDN_IPV6_URL=file:///path/ips-v6 \
#     ./scripts/fetch-real-ip-ranges.sh /tmp/qnero-real-ip.conf
set -euo pipefail

out="${1:-/etc/nginx/qnero-real-ip.conf}"
v4_url="${QNERO_CDN_IPV4_URL:-https://www.cloudflare.com/ips-v4}"
v6_url="${QNERO_CDN_IPV6_URL:-https://www.cloudflare.com/ips-v6}"
# Cloudflare publishes about fifteen IPv4 and seven IPv6 ranges. A fetch that
# comes back with two of them is an error page or a truncated read, and writing
# it would trust a range at random and leave the real edges untrusted.
minimum="${QNERO_CDN_MIN_RANGES:-8}"

fetch() {
    local url="$1"
    if ! curl -fsS --max-time 30 "$url"; then
        echo "fetching $url failed. The ranges are public; QNERO_CDN_IPV4_URL and" >&2
        echo "QNERO_CDN_IPV6_URL accept a file:// URL for a copy kept elsewhere." >&2
        exit 1
    fi
}

ranges="$(
    { fetch "$v4_url"; fetch "$v6_url"; } \
        | tr -d '\r' \
        | grep -E '^[0-9a-fA-F:.]+/[0-9]{1,3}$' \
        || true
)"

count="$(printf '%s\n' "$ranges" | grep -c . || true)"
if [ "$count" -lt "$minimum" ]; then
    echo "only $count usable ranges came back, and $minimum is the floor." >&2
    echo "Nothing was written: a short list is worse than no list, because it" >&2
    echo "passes nginx -t while most callers still read as the CDN." >&2
    exit 1
fi

tmp="$(mktemp "${TMPDIR:-/tmp}/qnero-real-ip.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
    echo "# Generated by scripts/fetch-real-ip-ranges.sh on $(date -u +%Y-%m-%d)."
    echo "# Sources: $v4_url"
    echo "#          $v6_url"
    echo "#"
    echo "# Every address in this list is believed when it says, in a"
    echo "# CF-Connecting-IP header, who the real caller is. Regenerate it when"
    echo "# the CDN publishes a change."
    printf '%s\n' "$ranges" | sed 's/^/set_real_ip_from /; s/$/;/'
} > "$tmp"

install -m 0644 "$tmp" "$out"
echo "wrote $out with $count ranges"
echo
echo "Then, and not before:"
echo "  sudo nginx -t && sudo systemctl reload nginx"
